# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contextualCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('feature', models.CharField(choices=[('0', 'title'), ('1', 'content')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('contextualCandidates', models.ManyToManyField(to='app.contextualCandidates')),
            ],
        ),
        migrations.CreateModel(
            name='structuralCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('contextualCandidates', models.ManyToManyField(to='app.contextualCandidates')),
            ],
        ),
        migrations.CreateModel(
            name='wordCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('feature', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='structuralCandidates',
            field=models.ManyToManyField(to='app.structuralCandidates'),
        ),
        migrations.AddField(
            model_name='link',
            name='wordCandidates',
            field=models.ManyToManyField(to='app.wordCandidate'),
        ),
        migrations.AddField(
            model_name='contextualcandidates',
            name='wordCandidates',
            field=models.ManyToManyField(to='app.wordCandidate'),
        ),
    ]
