# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextualcandidates',
            name='order',
        ),
        migrations.RemoveField(
            model_name='link',
            name='contextualCandidates',
        ),
        migrations.RemoveField(
            model_name='link',
            name='wordCandidates',
        ),
        migrations.RemoveField(
            model_name='structuralcandidates',
            name='order',
        ),
        migrations.AlterField(
            model_name='structuralcandidates',
            name='tag',
            field=models.CharField(choices=[('0', 'title'), ('1', 'document'), ('2', 'content'), ('3', 'reference')], default='2', max_length=2),
        ),
    ]
