# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170206_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
