# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170212_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceType', models.CharField(choices=[('0', 'url'), ('1', 'document/attachment')], default='0', max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='webSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryText', models.CharField(max_length=100)),
                ('results', models.ManyToManyField(to='app.WebResource')),
            ],
        ),
    ]
