# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_webresource_websearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='webresource',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='webresource',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
