# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170213_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webresource',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
